
package application.form.other;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import com.formdev.flatlaf.FlatClientProperties;
import javax.sound.sampled.LineUnavailableException;

import raven.toast.Notifications;
import Morsecode.MorsecodeLogic;
/**
 *
 * @author RATUL
 */
public class Morsecode extends javax.swing.JPanel implements KeyListener {
    private MorsecodeLogic logic=new MorsecodeLogic();
    public Morsecode() {
        initComponents();

        Title.putClientProperty(FlatClientProperties.STYLE, ""
                + "font: 130% $h1.font");

        ChangeButton.putClientProperty(FlatClientProperties.STYLE, ""
            + "borderWidth:0;"
            + "focusWidth:0;");
        ChangeButton.setBackground(Color.decode("#0FA4AF"));

        ChangeButton.putClientProperty( "JButton.buttonType", "roundRect" );
        TextBox.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT,"Input your text here");
        TextBox.putClientProperty(FlatClientProperties.STYLE, ""+ "font: $h2.font");
        TextBox.setEditable(true);

        Outputbox.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT,"Your morse code will be here");
        Outputbox.setEditable(false);
        Outputbox.putClientProperty(FlatClientProperties.STYLE, ""+ "font: 130% $h2.font;");

        TextBox.setLineWrap(true);
        TextBox.setWrapStyleWord(true);

        Outputbox.setLineWrap(true);
        Outputbox.setWrapStyleWord(true);

        ChangeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangeButtonActionPerformed(evt);
            }
        });
        Playsound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                 PlaysoundActionPerformed(evt);
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Ed itor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background1 = new MiscItem.BACKGOUND.Background();
        Title = new javax.swing.JLabel();
        jPanel1 = new application.form.other.pannelcolor("#90AEAD");
        inptutboxpane1 = new javax.swing.JScrollPane();
        Outputbox = new javax.swing.JTextArea();
        inptutboxpane = new javax.swing.JScrollPane();
        TextBox = new javax.swing.JTextArea();
        Playsound = new MiscItem.swing.Button();
        ChangeButton = new MiscItem.swing.Button();

        Title.setText("TEXT TO MORSECODE");

        jPanel1.setBackground(new java.awt.Color(51, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1000, 1000));
        jPanel1.setOpaque(false);

        Outputbox.setColumns(20);
        Outputbox.setRows(5);
        Outputbox.setMaximumSize(new java.awt.Dimension(600, 600));
        inptutboxpane1.setViewportView(Outputbox);

        TextBox.setColumns(20);
        TextBox.setRows(5);
        TextBox.setMaximumSize(new java.awt.Dimension(600, 600));
        inptutboxpane.setViewportView(TextBox);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(inptutboxpane, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)
                    .addComponent(inptutboxpane1))
                .addGap(40, 40, 40))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(inptutboxpane, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(inptutboxpane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        Playsound.setText("PLAY SOUND");

        ChangeButton.setText("CONVERT");

        javax.swing.GroupLayout background1Layout = new javax.swing.GroupLayout(background1);
        background1.setLayout(background1Layout);
        background1Layout.setHorizontalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background1Layout.createSequentialGroup()
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(background1Layout.createSequentialGroup()
                        .addContainerGap(140, Short.MAX_VALUE)
                        .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(background1Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(Playsound, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ChangeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        background1Layout.setVerticalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ChangeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Playsound, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents



    private  void ChangeButtonActionPerformed(java.awt.event.ActionEvent evt) {
        if (TextBox.getText().isEmpty()) {
            Notifications.getInstance().show(Notifications.Type.ERROR, "Please Enter Your Text Here");
            return;
        }
        Outputbox.setText(logic.getMorseCode(TextBox.getText()));
    }

    private void PlaysoundActionPerformed(java.awt.event.ActionEvent evt) {
        if(Outputbox.getText().isEmpty()) {
            Notifications.getInstance().show(Notifications.Type.WARNING, "No Morse Code Found");
            return;
        }
        ChangeButton.setEnabled(false);
        Playsound.setEnabled(false);
        new Thread(() -> {
            try {
                logic.playSound(new String[]{Outputbox.getText()});
            } catch (LineUnavailableException | InterruptedException ex) {
                Notifications.getInstance().show(Notifications.Type.WARNING, "Error playing sound: " + ex.getMessage());
            } finally {
                ChangeButton.setEnabled(true);
                Playsound.setEnabled(true);
            }
        }).start();
            Notifications.getInstance().show(Notifications.Type.INFO, "Sound is loading please wait");
    }

    @Override
    public void keyTyped(KeyEvent e) {

    }

    @Override
    public void keyPressed(KeyEvent e) {

    }

    @Override
    public void keyReleased(KeyEvent e) {
        if(e.getKeyCode() != KeyEvent.VK_SHIFT){
            String inputText = TextBox.getText();
            Outputbox.setText(new MorsecodeLogic().getMorseCode(inputText));
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private MiscItem.swing.Button ChangeButton;
    private javax.swing.JTextArea Outputbox;
    private MiscItem.swing.Button Playsound;
    private javax.swing.JTextArea TextBox;
    private javax.swing.JLabel Title;
    private MiscItem.BACKGOUND.Background background1;
    private javax.swing.JScrollPane inptutboxpane;
    private javax.swing.JScrollPane inptutboxpane1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
