/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package application.form.other.OneTime;

import com.formdev.flatlaf.FlatClientProperties;
import java.awt.Color;
import javax.swing.JTextArea;

/**
 *
 * @author RATUL
 */
public class OneTImeMsgbox extends javax.swing.JPanel {

    public OneTImeMsgbox(String s) {
        initComponents();
        //setBackground(new Color(2, 128, 144, 150));
        msg.setText(s);
        key.setLineWrap(true);
        key.setWrapStyleWord(true);
    }

    public void setkey(String s){
        key.setText(s);
    }
    public JTextArea keyseting(){
        return key;
    }
    public void Keyedit(Boolean flag){
        key.setEditable(flag);
    }

    public String getkey(){
        return key.getText();
    }
    public  void clearkey(){
        key.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        msg = new javax.swing.JTextPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        key = new javax.swing.JTextArea();

        msg.setOpaque(false);

        key.setColumns(20);
        key.setRows(5);
        jScrollPane1.setViewportView(key);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                    .addComponent(msg))
                .addGap(72, 72, 72))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(msg, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                .addGap(29, 29, 29))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea key;
    private javax.swing.JTextPane msg;
    // End of variables declaration//GEN-END:variables
}
